// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxF90GiJNrPMIRwumC4fU9CxqDCNkBMM',
    appId: '1:583076737255:web:edf3aac291caecac037242',
    messagingSenderId: '583076737255',
    projectId: 'artgallery-7acd3',
    authDomain: 'artgallery-7acd3.firebaseapp.com',
    storageBucket: 'artgallery-7acd3.appspot.com',
    measurementId: 'G-FCP04FBEES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj44F_hS5GVGm6D6r-W2joFqQYptAGvjE',
    appId: '1:583076737255:android:d5dd04f668e99704037242',
    messagingSenderId: '583076737255',
    projectId: 'artgallery-7acd3',
    storageBucket: 'artgallery-7acd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsrTo1Le6Q3eKnuQUq3Xzd3VRwEjXS6yk',
    appId: '1:583076737255:ios:5c6825d03b396921037242',
    messagingSenderId: '583076737255',
    projectId: 'artgallery-7acd3',
    storageBucket: 'artgallery-7acd3.appspot.com',
    iosBundleId: 'com.example.artGalary',
  );
}
